### ISSUE TITLE
Plexus team to confirm all plexus-interop code resides in the plexus-interop repository

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/plexus-interop#116]
### Description of Problem:
As part of a code consolidation exercise and repo migration to FINOS, the FINOS team would like to confirm all code related to plexus-interop resides in the plexus-interop repository.

If any plexus-interop code resides in unrelated repositories, such as finos-plexus.github.io, the code should be migrated into plexus-interop.

**Comment by udalmik** [comment]
Hi @mcleo-d !

I confirm that all Plexus Interop related code resides in plexus-interop repository and do not rely on other repos. 

Closing the issue as of now, please let me know in case  of further clarification required.

Thank you!

**Comment by mcleo-d** [comment]
Thank you @udalmik 👍
