### ISSUE TITLE
Plexus team to confirm Plexus Desktop Interop API project code

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/plexus-interop#117]
### Description of Problem:
As part of a code consolidation exercise and repo migration to FINOS, the FINOS team would like to reconfirm the location of the **Plexus Desktop Interop API** prior to the migration of repositories.  

Can the Plexus team confirm the following TypeScript file relates to the API contribution and also provide details of any other related API contributions prior to consolidation and migration. 

https://github.com/finos-plexus/finos-plexus.github.io/blob/master/client-api/client-api.ts

**Comment by mcleo-d** [comment]
Hi @udalmik

Is the question above something you can answer? 🤔

Thanks!

James.

**Comment by udalmik** [comment]
Hi @mcleo-d 

Yes, this (and only this) file relates to API contribution, all other content in this repo relates to demo projects.

Thank you, Mikhail

**Comment by mcleo-d** [comment]
Thank you for confirming @udalmik 😸 👍
