### ISSUE TITLE
Plexus PMC to confirm life cycle status of the Plexus Interop Project

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/plexus-interop#118]
### Description of Problem:
The current lifecycle stage of the Plexus Interop Project in the project metadata is "INCUBATING", but there's reason to believe this status should be "ACTIVE". 

### Potential Solutions:
Can the Plexus PMC lead review the revised FINOS activation life cycle criteria and recommend the PMC officially votes to move the project to "ACTIVE" based on the revised criteria.

https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530376/Activation

Alternatively, the Plexus PMC can suggest the project stays in "INCUBATING", but will need to suggest the steps needed, based on the criteria, to move the project to active 
- i.e., propose the plan to get the project from "INCUBATING" to "ACTIVE" and who specifically needs to do what when

**Comment by mcleo-d** [comment]
Similar PMC issue to #121

**Comment by paulwhitby** [comment]
Actively pursuing Activation, driven by @mcleo-d
