### ISSUE TITLE
Development Process

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/plexus-interop#150]
The Project adopts best-of-breed standards of distributed software development, including but not limited to:

- [x] semantic versioning
- [x] tagging / branch protection
- [x] continuous integration ("CI") and continuous delivery ("CD") where applicable
- [x] If Project Team choses not to use the FINOS provided [Open Developer Platform (GitHub)](https://github.com/finos/open-developer-platform) and [Open Developer Platform(wiki)](https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/243859459/Open+Developer+Platform+Project), a comparable SDLC should be adopted and made available.

**Comment by udalmik** [comment]
**Tagging / branch protection**
Tag created for each release. New dev is only done via PRs with all required approvals.

**Comment by udalmik** [comment]
**Continuous integration ("CI") and continuous delivery ("CD") where applicable**
**SDLC Process**
CI/CD pipeline is defined. Each PR and merge to master triggers build/integration tests. Each GH release triggers new versions of binaries publishing.

**Comment by udalmik** [comment]
**Semantic versioning**
Semantic versioning is used, the only leftover is to use separate versions, this is covered by #151 and #168 and #159.

**Comment by mcleo-d** [comment]
Hi @udalmik - It'll be great if you could speak to @paulwhitby on whether this is a dependency for FINOS activation. Many thanks, James 👍  

> **Semantic versioning**
> Semantic versioning is used, the only leftover is to use separate versions, this is covered by #151 and #168 and #159.

**Comment by mcleo-d** [comment]
> Hi @udalmik - It'll be great if you could speak to @paulwhitby on whether this is a dependency for FINOS activation. Many thanks, James 👍

@udalmik - I have reopened this story until the question above has been answered by @paulwhitby or @kryusvy.

Many thanks,

James.

**Comment by mcleo-d** [comment]
Hi @udalmik,

This is a conversation for you to have with @paulwhitby and @kryusvy to confirm whether it's a hard dependency for activation or can be handled later?

Many thanks.

James.

**Comment by udalmik** [comment]
As discussed, separate modules versioning (#168 ) is not a blocker for this item, just a better way of moving forward. We are complied with semantic versioning in any case.
