### ISSUE TITLE
Build and Release

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/plexus-interop#151]
### Plexus demonstrates the following
- [x] The Project code/documentation release process is automated or at lest well documented

**If code is published ... _(which applies to Plexus)_**
- [ ] Publicly redistributed release binaries should be listed or referred to in the documentation. e.g. 
  * Under the FINOS namespace
  * In an artefact repository or package manager, e.g. 
    * NPM
    * Maven Central
    * etc

**Comment by udalmik** [comment]
**The Project code/documentation release process is automated or at lest well documented**
Release process is fully automated, creation of GH release triggers publishing of new binaries

**Comment by udalmik** [comment]
**Publicly redistributed release binaries should be listed in an artefact repository or package manager**
NPM Packages
https://www.npmjs.com/search?q=plexus-interop
Nuget Packages
https://www.nuget.org/packages?q=Plexus
