### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mcleo-d** [finos-plexus/plexus-interop#153]
The README.md must include or reference up to date:

- [ ] End user docs including ...
  * A description of the software 
  * Feature overview 
  * Installation & configuration instructions
- [ ] Developer docs including links to other external systems (further docs, wiki, CI & validation tools, artefact repository, change log / history, etc.)
- [ ] Where possible badges (e.g. from shields.io) are encouraged
- [ ] Sample code explaining how to use the project, library, standard, SDK, etc.

**Comment by udalmik** [comment]
**End user docs**
Extensive documentation is provided, including features overview, including step by step Quick Start tutorial.

**Developer docs including links to other external systems (further docs, wiki, CI & validation tools, artifact repository, change log / history, etc.)**
Dev docs provided with instructions on core modules and how to build software.

**Where possible badges (e.g. from shields.io) are encouraged**
shields.io badges are used

**Sample code explaining how to use the project, library, standard, SDK, etc.**
Examples are provided, all main invocation flows are also described with e2e tests using Generated Clients
